// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/links/links.proto

package links

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Link struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uri           string                 `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Link) Reset() {
	*x = Link{}
	mi := &file_proto_links_links_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Link) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Link) ProtoMessage() {}

func (x *Link) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Link.ProtoReflect.Descriptor instead.
func (*Link) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{0}
}

func (x *Link) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type LinkEntry struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Link  *Link                  `protobuf:"bytes,1,opt,name=link,proto3" json:"link,omitempty"`
	// To make processing the redirect faster, store the
	// number of required path segments for replacement.
	RequiredPaths int32 `protobuf:"varint,2,opt,name=required_paths,json=requiredPaths,proto3" json:"required_paths,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LinkEntry) Reset() {
	*x = LinkEntry{}
	mi := &file_proto_links_links_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LinkEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LinkEntry) ProtoMessage() {}

func (x *LinkEntry) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LinkEntry.ProtoReflect.Descriptor instead.
func (*LinkEntry) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{1}
}

func (x *LinkEntry) GetLink() *Link {
	if x != nil {
		return x.Link
	}
	return nil
}

func (x *LinkEntry) GetRequiredPaths() int32 {
	if x != nil {
		return x.RequiredPaths
	}
	return 0
}

type Links struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Links         map[string]*Link       `protobuf:"bytes,1,rep,name=links,proto3" json:"links,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Links) Reset() {
	*x = Links{}
	mi := &file_proto_links_links_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Links) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Links) ProtoMessage() {}

func (x *Links) ProtoReflect() protoreflect.Message {
	mi := &file_proto_links_links_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Links.ProtoReflect.Descriptor instead.
func (*Links) Descriptor() ([]byte, []int) {
	return file_proto_links_links_proto_rawDescGZIP(), []int{2}
}

func (x *Links) GetLinks() map[string]*Link {
	if x != nil {
		return x.Links
	}
	return nil
}

var File_proto_links_links_proto protoreflect.FileDescriptor

const file_proto_links_links_proto_rawDesc = "" +
	"\n" +
	"\x17proto/links/links.proto\x12\x05links\"\x18\n" +
	"\x04Link\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"S\n" +
	"\tLinkEntry\x12\x1f\n" +
	"\x04link\x18\x01 \x01(\v2\v.links.LinkR\x04link\x12%\n" +
	"\x0erequired_paths\x18\x02 \x01(\x05R\rrequiredPaths\"}\n" +
	"\x05Links\x12-\n" +
	"\x05links\x18\x01 \x03(\v2\x17.links.Links.LinksEntryR\x05links\x1aE\n" +
	"\n" +
	"LinksEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12!\n" +
	"\x05value\x18\x02 \x01(\v2\v.links.LinkR\x05value:\x028\x01B\x1cZ\x1ajdtw.dev/links/proto/linksb\x06proto3"

var (
	file_proto_links_links_proto_rawDescOnce sync.Once
	file_proto_links_links_proto_rawDescData []byte
)

func file_proto_links_links_proto_rawDescGZIP() []byte {
	file_proto_links_links_proto_rawDescOnce.Do(func() {
		file_proto_links_links_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_links_links_proto_rawDesc), len(file_proto_links_links_proto_rawDesc)))
	})
	return file_proto_links_links_proto_rawDescData
}

var file_proto_links_links_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_links_links_proto_goTypes = []any{
	(*Link)(nil),      // 0: links.Link
	(*LinkEntry)(nil), // 1: links.LinkEntry
	(*Links)(nil),     // 2: links.Links
	nil,               // 3: links.Links.LinksEntry
}
var file_proto_links_links_proto_depIdxs = []int32{
	0, // 0: links.LinkEntry.link:type_name -> links.Link
	3, // 1: links.Links.links:type_name -> links.Links.LinksEntry
	0, // 2: links.Links.LinksEntry.value:type_name -> links.Link
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_proto_links_links_proto_init() }
func file_proto_links_links_proto_init() {
	if File_proto_links_links_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_links_links_proto_rawDesc), len(file_proto_links_links_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_links_links_proto_goTypes,
		DependencyIndexes: file_proto_links_links_proto_depIdxs,
		MessageInfos:      file_proto_links_links_proto_msgTypes,
	}.Build()
	File_proto_links_links_proto = out.File
	file_proto_links_links_proto_goTypes = nil
	file_proto_links_links_proto_depIdxs = nil
}
